# Generated by Django 6.0.1 on 2026-01-25 22:59

import django.contrib.postgres.fields.ranges
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Engineer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('team', models.CharField(blank=True, max_length=100, null=True)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('last_active', models.DateTimeField(blank=True, null=True)),
                ('recs', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'engineers',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=512)),
                ('checksum', models.CharField(blank=True, max_length=255, null=True)),
                ('line_count', models.IntegerField(blank=True, null=True)),
                ('ast_summary', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'files',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('dir_path', models.CharField(blank=True, max_length=512, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('risk_score', models.FloatField(blank=True, null=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('recs', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'modules',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Repo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('language', models.CharField(blank=True, max_length=100, null=True)),
                ('risk_score', models.FloatField(blank=True, null=True)),
                ('rec', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'repos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(blank=True, choices=[('LANGUAGE', 'Language'), ('FRAMEWORK', 'Framework'), ('TOOL', 'Tool'), ('PLATFORM', 'Platform')], max_length=50, null=True)),
            ],
            options={
                'db_table': 'skills',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FileDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_package_id', models.IntegerField(blank=True, null=True)),
                ('dependency_type', models.CharField(blank=True, choices=[('INTERNAL', 'Internal'), ('EXTERNAL', 'External')], max_length=50, null=True)),
                ('raw_import_statement', models.CharField(blank=True, max_length=512, null=True)),
                ('importer_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies_imported', to='git_blame_ingestion_app.file')),
                ('resolved_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_by', to='git_blame_ingestion_app.file')),
            ],
            options={
                'db_table': 'file_dependencies',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LineOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('line_range', django.contrib.postgres.fields.ranges.IntegerRangeField()),
                ('last_updated_commit', models.TextField(blank=True, null=True)),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='git_blame_ingestion_app.engineer')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='git_blame_ingestion_app.file')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_lines', to='git_blame_ingestion_app.engineer')),
            ],
            options={
                'db_table': 'line_ownership',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='file',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='git_blame_ingestion_app.module'),
        ),
        migrations.AddField(
            model_name='module',
            name='repo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='git_blame_ingestion_app.repo'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lines', models.IntegerField(blank=True, null=True)),
                ('file_path', models.CharField(blank=True, max_length=512, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('engineer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='git_blame_ingestion_app.engineer')),
            ],
            options={
                'db_table': 'reviews',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ModuleSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(blank=True, null=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='git_blame_ingestion_app.module')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='git_blame_ingestion_app.skill')),
            ],
            options={
                'db_table': 'module_skills',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EngineerSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(blank=True, null=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='git_blame_ingestion_app.engineer')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='git_blame_ingestion_app.skill')),
            ],
            options={
                'db_table': 'engineer_skills',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FileContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(blank=True, choices=[('DESIGNED', 'Designed'), ('WROTE', 'Wrote'), ('REVIEWED', 'Reviewed')], max_length=50, null=True)),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='git_blame_ingestion_app.engineer')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='git_blame_ingestion_app.file')),
            ],
            options={
                'db_table': 'file_contributions',
                'managed': True,
                'unique_together': {('engineer', 'file', 'interaction_type')},
            },
        ),
        migrations.CreateModel(
            name='FileOwnershipMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lines_owned', models.IntegerField(default=0)),
                ('lines_owned_percentage', models.FloatField(blank=True, null=True)),
                ('commit_count', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('DESIGNED', 'Designed'), ('WROTE', 'Wrote'), ('REVIEWED', 'Reviewed')], max_length=50)),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='git_blame_ingestion_app.engineer')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='git_blame_ingestion_app.file')),
            ],
            options={
                'db_table': 'file_ownership_metrics',
                'managed': True,
                'unique_together': {('file', 'engineer', 'type')},
            },
        ),
        migrations.CreateModel(
            name='ModuleContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(blank=True, choices=[('DESIGNED', 'Designed'), ('WROTE', 'Wrote'), ('REVIEWED', 'Reviewed')], max_length=50, null=True)),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='git_blame_ingestion_app.engineer')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='git_blame_ingestion_app.module')),
            ],
            options={
                'db_table': 'module_contributions',
                'managed': True,
                'indexes': [models.Index(fields=['module', 'interaction_type'], name='idx_contributions_module_id')],
                'unique_together': {('engineer', 'module', 'interaction_type')},
            },
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['name'], name='idx_modules_name'),
        ),
        migrations.AlterUniqueTogether(
            name='moduleskill',
            unique_together={('module', 'skill')},
        ),
        migrations.AlterUniqueTogether(
            name='engineerskill',
            unique_together={('engineer', 'skill')},
        ),
    ]
