# Generated by Django 5.0.1 on 2026-02-19 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git_blame_ingestion_app', '0002_repo_owner_alter_engineer_id_alter_engineerskill_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleOwnershipMetric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lines_owned', models.IntegerField(default=0)),
                ('lines_owned_percentage', models.FloatField(blank=True, null=True)),
                ('commit_count', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('DESIGNED', 'Designed'), ('WROTE', 'Wrote'), ('REVIEWED', 'Reviewed')], max_length=50)),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='git_blame_ingestion_app.engineer')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='git_blame_ingestion_app.module')),
            ],
            options={
                'db_table': 'module_ownership_metrics',
                'managed': True,
                'unique_together': {('module', 'engineer', 'type')},
            },
        ),
    ]
