# Generated by Django 5.0.1 on 2026-02-21 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git_blame_ingestion_app', '0005_alter_modulecontribution_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='module',
            field=models.ForeignKey(db_column='module_id', on_delete=django.db.models.deletion.CASCADE, related_name='files', to='git_blame_ingestion_app.module'),
        ),
        migrations.RenameField(
            model_name='file',
            old_name='module',
            new_name='module_id',
        ),
    ]
