# Generated by Django 5.0.1 on 2026-02-21 22:21

from django.db import migrations


from django.db.models import Count

def remove_duplicates(apps, schema_editor):
    Module = apps.get_model('git_blame_ingestion_app', 'Module')
    duplicates = (
        Module.objects.values('repo_id', 'name')
        .annotate(name_count=Count('id'))
        .filter(name_count__gt=1)
    )
    for duplicate in duplicates:
        # Get all instances of this duplicate
        modules = Module.objects.filter(
            repo_id=duplicate['repo_id'], 
            name=duplicate['name']
        ).order_by('id')
        
        # Keep the first one, delete the rest
        first_module = modules.first()
        modules.exclude(id=first_module.id).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('git_blame_ingestion_app', '0007_alter_engineer_id_alter_engineerskill_id_and_more'),
    ]

    operations = [
        migrations.RunPython(remove_duplicates),
    ]
