# Generated by Django 5.0.1 on 2026-02-22 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git_blame_ingestion_app', '0009_alter_engineer_id_alter_engineerskill_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='inbound_coupling',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='file',
            name='is_brain_file',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='file',
            name='loc_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='file',
            name='module_density',
            field=models.FloatField(default=0.0),
        ),
    ]
