# Generated by Django 6.0.1 on 2026-02-27 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git_blame_ingestion_app', '0011_alter_engineer_id_alter_engineerskill_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='max_inheritance_depth',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='file',
            name='max_nesting_depth',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='file',
            name='structural_risk_score',
            field=models.IntegerField(default=0),
        ),
    ]
