# Generated by Django 6.0.1 on 2026-03-06 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git_blame_ingestion_app', '0012_file_max_inheritance_depth_file_max_nesting_depth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='change_frequency_raw',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='file',
            name='change_frequency_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='PullRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_pr_number', models.IntegerField()),
                ('title', models.CharField(blank=True, max_length=512, null=True)),
                ('merged_at', models.DateTimeField()),
                ('author_login', models.CharField(blank=True, max_length=255, null=True)),
                ('is_revert', models.BooleanField(default=False)),
                ('is_bot', models.BooleanField(default=False)),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pull_requests', to='git_blame_ingestion_app.repo')),
            ],
            options={
                'db_table': 'pull_requests',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PullRequestFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=512)),
                ('pull_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pr_files', to='git_blame_ingestion_app.pullrequest')),
            ],
            options={
                'db_table': 'pull_request_files',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='pullrequest',
            index=models.Index(fields=['repo', 'merged_at'], name='idx_pr_repo_merged_at'),
        ),
        migrations.AlterUniqueTogether(
            name='pullrequest',
            unique_together={('repo', 'github_pr_number')},
        ),
        migrations.AddIndex(
            model_name='pullrequestfile',
            index=models.Index(fields=['file_path'], name='idx_pr_file_path'),
        ),
        migrations.AlterUniqueTogether(
            name='pullrequestfile',
            unique_together={('pull_request', 'file_path')},
        ),
    ]
