# Generated by Django 6.0.1 on 2026-04-07 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git_blame_ingestion_app', '0015_structural_hubs'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='hub_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='file',
            name='knowledge_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='file',
            name='risk_score',
            field=models.FloatField(default=0.0),
        ),
    ]
