# Generated by Django 6.0.1 on 2026-04-09 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git_blame_ingestion_app', '0016_composite_risk_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('TODO', 'To Do'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved')], default='TODO', max_length=20)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_items', to='git_blame_ingestion_app.repo')),
            ],
            options={
                'db_table': 'action_items',
                'managed': True,
            },
        ),
    ]
