# Generated by Django 6.0.2 on 2026-05-07 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git_blame_ingestion_app', '0017_actionitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='assigned_designer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designed_modules', to='git_blame_ingestion_app.engineer'),
        ),
        migrations.AddField(
            model_name='module',
            name='assigned_reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_modules', to='git_blame_ingestion_app.engineer'),
        ),
        migrations.AddField(
            model_name='module',
            name='assigned_writer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='written_modules', to='git_blame_ingestion_app.engineer'),
        ),
        migrations.CreateModel(
            name='ModuleRoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='git_blame_ingestion_app.engineer')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='git_blame_ingestion_app.module')),
            ],
            options={
                'db_table': 'module_role_assignments',
                'managed': True,
            },
        ),
    ]
