# Generated by Antigravity

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('git_blame_ingestion_app', '0017_actionitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='repo',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
