databases:
  - name: swemap-db
    databaseName: swemap
    user: swemap_user
    plan: free

services:
  # 1. Managed Redis (Key-Value)
  - type: redis
    name: swemap-redis
    ipAllowList: []
    plan: free

  # 2. Django Web Service + Celery (Combined for $0 tier)
  - type: web
    name: swemap-web
    env: python
    plan: free
    buildCommand: "./django/backend/build.sh"
    # We run Celery in the background (&) and Gunicorn in the foreground!
    # Because & separates commands, we must use --chdir for gunicorn to find the code
    # We MUST set --concurrency=1 otherwise Celery preforks 8 times and instantly crashes the 512MB free tier!
    startCommand: "cd django/backend && celery -A backend worker -B --concurrency=1 -l info & gunicorn --chdir django/backend backend.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: swemap-db
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: swemap-redis
          property: connectionString
      - key: CELERY_RESULT_BACKEND
        fromService:
          type: redis
          name: swemap-redis
          property: connectionString
      - key: GITHUB_TOKEN
        sync: false
      - key: OLLAMA_BASE_URL
        value: "PLACEHOLDER_FOR_FUTURE_LLM_URL"
