"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

load_dotenv(Path(__file__).resolve().parent.parent / '.env')

# Celery Configuration
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')

from celery.schedules import crontab

# Set Celery timezone to CDT/CST
CELERY_TIMEZONE = 'America/New_York'

CELERY_BEAT_SCHEDULE = {
    'nightly-repo-recalculation': {
        'task': 'git_blame_ingestion_app.tasks.nightly_repo_recalculation',
        'schedule': crontab(hour=0, minute=0),  # 12:00 AM Midnight
    },
}

# GitHub Configuration
GITHUB_TOKEN = os.getenv('GITHUB_TOKEN')



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ch5hlj_-0l2fbju98__ovh*@4%2mx15*!a=+^&)n)81-i2g)$n'

# SECURITY WARNING: don't run with debug turned on in production!
# Automatically set DEBUG=False if running on Render.com
DEBUG = 'RENDER' not in os.environ

ALLOWED_HOSTS = ['*'] # In production, you can restrict this to your specific render URL


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',
    'git_blame_ingestion_app',
    'code_ownership',
    'risk_dashboard',
    'ninja',
    "corsheaders",
    'performance_profiling',
    'skill_analysis',
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",  # Must be as high as possible!
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

import dj_database_url

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'postgres'),
        'USER': os.getenv('DB_USER', 'postgres'),
        'PASSWORD': os.getenv('DB_PASSWORD', '0812'),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5432'),
    }
}

if os.getenv('DATABASE_URL'):
    DATABASES['default'] = dj_database_url.config(
        default=os.getenv('DATABASE_URL'),
        conn_max_age=600,
        conn_health_checks=True,
    )


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Skill Graph Configuration
_ARTIFACTS_DIR = BASE_DIR / 'skill_analysis' / 'artifacts'
_DATA_DIR = BASE_DIR.parent.parent / 'data'

SKILL_DATASETS = {
    'cso': {
        'csv_path': _DATA_DIR / 'CSO.3.4.1.csv',
        'builder': 'skill_analysis.services.cso_graph_builder.CSOGraphBuilder',
        'graph_path': _ARTIFACTS_DIR / 'cso_graph.pickle',
        'index_path': _ARTIFACTS_DIR / 'cso_vector_db.index',
        'mapping_path': _ARTIFACTS_DIR / 'cso_vector_mapping.json',
    },
    'conda': {
        'csv_path': _DATA_DIR / 'conda_skill_tree.csv',
        'builder': 'skill_analysis.services.skill_graph_builder.SkillGraphBuilder',
        'graph_path': _ARTIFACTS_DIR / 'conda_graph.pickle',
        'index_path': _ARTIFACTS_DIR / 'conda_vector_db.index',
        'mapping_path': _ARTIFACTS_DIR / 'conda_vector_mapping.json',
    },
}

# Legacy aliases (used by existing lazy accessors)
CSO_GRAPH_ARTIFACT_PATH = SKILL_DATASETS['cso']['graph_path']
CSO_VECTOR_INDEX_PATH = SKILL_DATASETS['cso']['index_path']
CSO_VECTOR_MAPPING_PATH = SKILL_DATASETS['cso']['mapping_path']

# Risk Dashboard Configuration
RISK_CONFIG = {
    "BUS_FACTOR_THRESHOLD": 90.0,
    "ABANDONED_CODE_THRESHOLD": 30.0,
    "ABANDONED_INACTIVE_DAYS": 90,
    "HEALTHY_SILO_TOP_MIN": 50.0,
    "HEALTHY_SILO_TOP_MAX": 70.0,
    "HEALTHY_SILO_OTHER_MIN": 10.0,
    "HEALTHY_SILO_OTHER_MAX": 20.0,
    # Change Frequency (File Churn)
    "CHURN_DECAY_H": 1.0,
    "CHURN_DECAY_L": 0.1,
    "CHURN_DECAY_X0": 21,
    "CHURN_DECAY_K": 0.5,
    "CHURN_LOOKBACK_DAYS": 180,
    "CHURN_HIGH_CAP_THRESHOLD": 2.0,
    "CHURN_HIGH_CAP_FALLBACK": 7,
    "CHURN_LOW_CAP_THRESHOLD": 0.1,
    "CHURN_LOW_CAP_FALLBACK": 3,
    "CHURN_QUIET_VARIANCE": 0.01,
    "CHURN_QUIET_DEFAULT": 3,
    "CHURN_HOTSPOT_THRESHOLD": 8,
    # Structural Hub Thresholds
    "GLOBAL_HUB_ABS_THRESHOLD": 30,       # N_F >= 30 incoming dependencies
    "GLOBAL_HUB_REL_THRESHOLD": 0.15,     # N_F >= 15% of all repo files
    "BOUNDARY_HUB_EXT_MIN": 5,            # E_F >= 5 external importers
    "BOUNDARY_HUB_EXT_RATIO": 0.80,       # E_F / (I_F + E_F) >= 80%
    "LOCAL_HUB_MIN_MODULE_SIZE": 3,        # S_M >= 3 sibling files
    "LOCAL_HUB_INTERNAL_RATIO": 0.50,      # I_F / S_M >= 50%
    "LOCAL_HUB_INTERNAL_DOMINANCE": 0.50,  # I_F / (I_F + E_F) >= 50%
    # Composite Risk Weights
    "RISK_WEIGHT_CHURN": 0.30,
    "RISK_WEIGHT_HUB": 0.40,
    "RISK_WEIGHT_KNOWLEDGE": 0.30,
    # Knowledge Score Thresholds
    "KNOWLEDGE_TOXIC_THRESHOLD": 90.0,
    "KNOWLEDGE_CONCENTRATED_THRESHOLD": 70.0,
    "KNOWLEDGE_MODERATE_THRESHOLD": 50.0,
    "KNOWLEDGE_DISTRIBUTED_SCORE": 1.0,
    "KNOWLEDGE_ABANDONED_MULTIPLIER": 1.5,
}

# Ollama (Local LLM) Configuration
OLLAMA_BASE_URL = os.getenv('OLLAMA_BASE_URL', 'http://localhost:11434/v1')
OLLAMA_MODEL = os.getenv('OLLAMA_MODEL', 'deepseek-r1:8b')
OLLAMA_TEMPERATURE = float(os.getenv('OLLAMA_TEMPERATURE', '0.2'))

# Logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{asctime} {levelname} {name} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'risk_dashboard': {
            'handlers': ['console'],
            'level': 'INFO',
        },
        'git_blame_ingestion_app': {
            'handlers': ['console'],
            'level': 'INFO',
        },
        'code_ownership': {
            'handlers': ['console'],
            'level': 'INFO',
        },
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}
